EducateAppChu/ViewModels/IntermediateCertificationTypes/CreateIntermediateCertificationTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateAppChu.ViewModels.IntermediateCertificationTypes
{
    public class CreateIntermediateCertificationTypeViewModel
    {
        [Required(ErrorMessage = "Введите название вида промежуточной аттестации")]
        [Display(Name = "Вид промежуточной аттестации")]
        public string InterCertType { get; set; }
    }
}

EducateAppChu/ViewModels/IntermediateCertificationTypes/EditIntermediateCertificationTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EducateAppChu.ViewModels.IntermediateCertificationTypes
{
    public class EditIntermediateCertificationTypeViewModel
    {
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите название вида промежуточной аттестации")]
        [Display(Name = "Вид промежуточной аттестации")]
        public string InterCertType { get; set; }

        public string IdUser { get; set; }
    }
}

EducateAppChu/Controllers/IntermediateCertificationTypesController.cs
using EducateAppChu.Models;

using EducateAppChu.Models.Data;

using EducateAppChu.ViewModels.IntermediateCertificationTypes;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;

using System.Linq;

using System.Threading.Tasks;

namespace EducateAppChu.Controllers

{

    [Authorize(Roles = "admin, registeredUser")]

    public class IntermediateCertificationTypesController : Controller

    {

        private readonly AppCtx _context;

        private readonly UserManager<User> _userManager;

        public IntermediateCertificationTypesController(AppCtx context,

        UserManager<User> user)

        {

            _context = context;

            _userManager = user;

        }

        // GET: FormsOfStudy
        public async Task<IActionResult> Index(IntermediateCertificationTypeSortState sortOrder = IntermediateCertificationTypeSortState.InterCertTypeAsc)
        {
            // находим информацию о пользователе, который вошел в систему по его имени
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // через контекст данных получаем доступ к таблице базы данных FormsOfStudy
            var intermediateCertificationTypes = _context.IntermediateCertificationTypes
                .Include(f => f.User)                // и связываем с таблицей пользователи через класс User
                .Where(f => f.IdUser == user.Id);     // устанавливается условие с выбором записей форм обучения текущего пользователя по его Id

            ViewData["InterCertTypeSort"] = sortOrder == IntermediateCertificationTypeSortState.InterCertTypeAsc ? IntermediateCertificationTypeSortState.InterCertTypeDesc : IntermediateCertificationTypeSortState.InterCertTypeAsc;

            intermediateCertificationTypes = sortOrder switch
            {
                IntermediateCertificationTypeSortState.InterCertTypeDesc => intermediateCertificationTypes.OrderByDescending(s => s.InterCertType),
                _ => intermediateCertificationTypes.OrderBy(s => s.InterCertType),
            };

            // возвращаем в представление полученный список записей
            return View(await intermediateCertificationTypes.AsNoTracking().ToListAsync());
        }

        //// GET: FormsOfStudy

        //public async Task<IActionResult> Index()

        //{

        //    // находим информацию о пользователе, который вошел в систему по его имени

        //    IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

        //    // через контекст данных получаем доступ к таблице базы данных FormsOfStudy

        //    var appCtx = _context.IntermediateCertificationTypes

        //    .Include(f => f.User) // и связываем с таблицей пользователи через класс User

        //    .Where(f => f.IdUser == user.Id) // устанавливается условие с выбором записей форм обучения текущего пользователя по его Id

        //    .OrderBy(f => f.InterCertType); // сортируем все записи по имени форм обучения

        //    // возвращаем в представление полученный список записей

        //    return View(await appCtx.ToListAsync());

        //}

        // GET: FormsOfStudy/Create

        public IActionResult Create()

        {

            return View();

        }

        [HttpPost]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(CreateIntermediateCertificationTypeViewModel model)

        {

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.IntermediateCertificationTypes

            .Where(f => f.IdUser == user.Id &&

            f.InterCertType == model.InterCertType).FirstOrDefault() != null)

            {

                ModelState.AddModelError("", "Введенный вид промежуточной аттестации уже существует");

            }

            if (ModelState.IsValid)

            {

                IntermediateCertificationType intermediateCertificationType = new()

                {

                    InterCertType = model.InterCertType,

                    IdUser = user.Id

                };

                _context.Add(intermediateCertificationType);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }

            return View(model);

        }

        // GET: FormsOfStudy/Edit/5

        public async Task<IActionResult> Edit(short? id)

        {

            if (id == null)

            {

                return NotFound();

            }

            var intermediateCertificationType = await _context.IntermediateCertificationTypes.FindAsync(id);

            if (intermediateCertificationType == null)

            {

                return NotFound();

            }

            EditIntermediateCertificationTypeViewModel model = new()

            {

                Id = intermediateCertificationType.Id,

                InterCertType = intermediateCertificationType.InterCertType,

                IdUser = intermediateCertificationType.IdUser

            };

            return View(model);

        }

        [HttpPost]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(short id, EditIntermediateCertificationTypeViewModel model)

        {

            IntermediateCertificationType intermediateCertificationType = await _context.IntermediateCertificationTypes.FindAsync(id);

            if (id != intermediateCertificationType.Id)

            {

                return NotFound();

            }

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.IntermediateCertificationTypes

            .Where(f => f.IdUser == user.Id &&

            f.InterCertType == model.InterCertType).FirstOrDefault() != null)

            {

                ModelState.AddModelError("", "Введенный вид промежуточной аттестации уже существует");

            }

            if (ModelState.IsValid)

            {

                try

                {

                    intermediateCertificationType.InterCertType = model.InterCertType;

                    _context.Update(intermediateCertificationType);

                    await _context.SaveChangesAsync();

                }

                catch (DbUpdateConcurrencyException)

                {

                    if (!IntermediateCertificationTypeExists(intermediateCertificationType.Id))

                    {

                        return NotFound();

                    }

                    else

                    {

                        throw;

                    }

                }

                return RedirectToAction(nameof(Index));

            }

            return View(model);

        }

        // GET: FormsOfStudy/Delete/5

        public async Task<IActionResult> Delete(short? id)

        {

            if (id == null)

            {

                return NotFound();

            }

            var intermediateCertificationType = await _context.IntermediateCertificationTypes

            .Include(f => f.User)

            .FirstOrDefaultAsync(m => m.Id == id);

            if (intermediateCertificationType == null)

            {

                return NotFound();

            }

            return View(intermediateCertificationType);

        }

        // POST: FormsOfStudy/Delete/5

        [HttpPost, ActionName("Delete")]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(short id)

        {

            var intermediateCertificationType = await _context.IntermediateCertificationTypes.FindAsync(id);

            _context.IntermediateCertificationTypes.Remove(intermediateCertificationType);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null)

            {

                return NotFound();

            }

            var intermediateCertificationType = await _context.IntermediateCertificationTypes

            .Include(f => f.User)

            .FirstOrDefaultAsync(m => m.Id == id);

            if (intermediateCertificationType == null)

            {

                return NotFound();

            }

            return PartialView(intermediateCertificationType);
        }

        //// GET: FormsOfStudy/Details/5

        //public async Task<IActionResult> Details(short? id)

        //{

        //    if (id == null)

        //    {

        //        return NotFound();

        //    }

        //    var intermediateCertificationType = await _context.IntermediateCertificationTypes

        //    .Include(f => f.User)

        //    .FirstOrDefaultAsync(m => m.Id == id);

        //    if (intermediateCertificationType == null)

        //    {

        //        return NotFound();

        //    }

        //    return View(intermediateCertificationType);

        //}

        private bool IntermediateCertificationTypeExists(short id)

        {

            return _context.IntermediateCertificationTypes.Any(e => e.Id == id);

        }

    }

}

EducateAppChu/Views/IntermediateCertificationTypes/Create.cshtml
@model EducateAppChu.ViewModels.IntermediateCertificationTypes.CreateIntermediateCertificationTypeViewModel
@{
    ViewData["Title"] = "Создание - Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="IntermediateCertificationTypes" asp-action="Index">Виды промежуточной аттестации</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление вида промежуточной аттестации
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form method="post" asp-controller="IntermediateCertificationTypes" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InterCertType" class="control-label"></label>
                <input asp-for="InterCertType" class="form-control" />
                <span asp-validation-for="InterCertType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateAppChu/Views/IntermediateCertificationTypes/Delete.cshtml
@model EducateAppChu.Models.Data.IntermediateCertificationType
@{
    ViewData["Title"] = "Удаление - Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="IntermediateCertificationTypes" asp-action="Index">Виды промежуточной аттестации</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление вида промежуточной аттестации
</h3>

<div>
    <h4>
        Вы уверены, что желаете удалить запись?<br />
        Все связанные данные будут удалены!
    </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.InterCertType)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.InterCertType)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </form>
</div>

EducateAppChu/Views/IntermediateCertificationTypes/Details.cshtml
@model EducateAppChu.Models.Data.IntermediateCertificationType

<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Просмотр вида промежуточной аттестации</h4>
        <button type="button" class="close" data-dismiss="modal">
            <i class="fas fa-times"></i>
        </button>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.InterCertType)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InterCertType)
            </dd>
        </dl>
    </div>
</div>

EducateAppChu/Views/IntermediateCertificationTypes/Edit.cshtml
@model EducateAppChu.ViewModels.IntermediateCertificationTypes.EditIntermediateCertificationTypeViewModel

@{
    ViewData["Title"] = "Изменение - Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="IntermediateCertificationTypes" asp-action="Index">Виды промежуточной аттестации</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение вида промежуточной аттестации
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-controller="IntermediateCertificationTypes" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InterCertType" class="control-label"></label>
                <input asp-for="InterCertType" class="form-control" />
                <span asp-validation-for="InterCertType" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IdUser" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateAppChu/Views/IntermediateCertificationTypes/Index.cshtml
@model IEnumerable<EducateAppChu.Models.Data.IntermediateCertificationType>

@{
    ViewData["Title"] = "Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item active">Виды промежуточной аттестации</li>
    </ol>
</nav>
<h2>Виды промежуточной аттестации</h2>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<h6>
    <a class="btn text-dark" asp-action="Create">
        <i class="far fa-plus-square"></i>  Добавить вид промежуточной аттестации
    </a>
</h6>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.InterCertTypeSort">
                    @Html.DisplayNameFor(model => model.InterCertType)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.InterCertType)
                </td>
                <td>
                    <a class="btn text-dark detailsId" asp-action="Details" asp-route-id="@item.Id" title="Посмотреть подробнее" id="details">
                        <i class="far fa-eye"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Edit" asp-route-id="@item.Id" title="Редактировать">
                        <i class="fas fa-pencil-alt"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Delete" asp-route-id="@item.Id" title="Удалить">
                        <i class="far fa-minus-square"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".detailsId").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}