EducateAppChu/Models/Data/Group.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EducateAppChu.Models.Data
{
    public class Group
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "ИД")]
        public short Id { get; set; }

        [Required]
        [Display(Name = "Специальность")]
        public short IdSpecialty { get; set; }

        [Required(ErrorMessage = "Введите название группы")]
        [Display(Name = "Группа")]
        public string Name { get; set; }

        [Display(Name = "Кол. студентов")]
        [Range(1, 255, ErrorMessage = "Введите число от 1 до 255")]
        public byte? CountOfStudents { get; set; }

        [Required(ErrorMessage = "Введите год поступления")]
        [Display(Name = "Год пост.")]
        [Range(1950, 9999, ErrorMessage = "Введите корректное число")]
        public short YearOfAdmission { get; set; }

        [Required(ErrorMessage = "Введите год выпуска")]
        [Display(Name = "Год выпуска")]
        [Range(1950, 9999, ErrorMessage = "Введите корректное число")]
        public short YearOfIssue { get; set; }

        [Required(ErrorMessage = "Введите имя классного руководителя")]
        [Display(Name = "Имя кл. рук.")]
        [DataType(DataType.Text)]
        public string ClassTeacher { get; set; }

        [Display(Name = "Контакты кл. рук.")]
        public string ContactsTeacher { get; set; }


        // Навигационные свойства
        [Display(Name = "Специальность")]
        [ForeignKey("IdSpecialty")]
        public Specialty Specialty { get; set; }
    }
}

EducateAppChu/ViewModels/Groups/CreateGroupViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EducateAppChu.ViewModels.Groups
{
    public class CreateGroupViewModel
    {
        [Required]
        [Display(Name = "Выберите форму обучения")]
        public short IdFormOfStudy { get; set; }

        [Required]
        [Display(Name = "Выберите специальность")]
        public short IdSpecialty { get; set; }

        [Required(ErrorMessage = "Введите название группы")]
        [Display(Name = "Группа")]
        public string Name { get; set; }

        [Display(Name = "Количество студентов")]
        [Range(1, 255, ErrorMessage = "Введите число от 1 до 255")]
        public byte? CountOfStudents { get; set; }

        [Required(ErrorMessage = "Введите год поступления")]
        [Display(Name = "Год поступления")]
        [Range(1950, 9999, ErrorMessage = "Введите корректное число")]
        public short YearOfAdmission { get; set; }

        [Required(ErrorMessage = "Введите год выпуска")]
        [Display(Name = "Год выпуска")]
        [Range(1950, 9999, ErrorMessage = "Введите корректное число")]
        public short YearOfIssue { get; set; }

        [Required(ErrorMessage = "Введите имя классного руководителя")]
        [Display(Name = "Имя классного руководителя")]
        [DataType(DataType.Text)]
        public string ClassTeacher { get; set; }

        [Display(Name = "Контакты классного руководителя")]
        public string ContactsTeacher { get; set; }
    }
}

EducateAppChu/ViewModels/Groups/EditGroupViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EducateAppChu.ViewModels.Groups
{
    public class EditGroupViewModel
    {
        public short Id { get; set; }

        [Required]
        [Display(Name = "Выберите форму обучения")]
        public short IdFormOfStudy { get; set; }

        [Required]
        [Display(Name = "Выберите специальность")]
        public short IdSpecialty { get; set; }

        [Required(ErrorMessage = "Введите название группы")]
        [Display(Name = "Группа")]
        public string Name { get; set; }

        [Display(Name = "Количество студентов")]
        [Range(1, 255, ErrorMessage = "Введите число от 1 до 255")]
        public byte? CountOfStudents { get; set; }

        [Required(ErrorMessage = "Введите год поступления")]
        [Display(Name = "Год поступления")]
        [Range(1950, 9999, ErrorMessage = "Введите корректное число")]
        public short YearOfAdmission { get; set; }

        [Required(ErrorMessage = "Введите год выпуска")]
        [Display(Name = "Год выпуска")]
        [Range(1950, 9999, ErrorMessage = "Введите корректное число")]
        public short YearOfIssue { get; set; }

        [Required(ErrorMessage = "Введите имя классного руководителя")]
        [Display(Name = "Имя классного руководителя")]
        [DataType(DataType.Text)]
        public string ClassTeacher { get; set; }

        [Display(Name = "Контакты классного руководителя")]
        public string ContactsTeacher { get; set; }
    }
}

EducateAppChu/Controllers/GroupsController.cs
using ClosedXML.Excel;
using EducateAppChu.Models;
using EducateAppChu.Models.Data;
using EducateAppChu.ViewModels.Groups;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EducateAppChu.Controllers
{
    [Authorize(Roles = "admin, registeredUser")]
    public class GroupsController : Controller
    {
        private readonly AppCtx _context;
        private readonly UserManager<User> _userManager;

        public GroupsController(AppCtx context, UserManager<User> user)
        {
            _context = context;
            _userManager = user;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            var appCtx = _context.Groups
                .Include(s => s.Specialty.FormOfStudy)
                .Where(w => w.Specialty.FormOfStudy.IdUser == user.Id)
                .OrderByDescending(f => f.YearOfAdmission)
                .ThenBy(f => f.YearOfIssue)
                .ThenByDescending(f => f.Name);

            return View(await appCtx.ToListAsync());
        }

        // GET: Groups/Create
        public async Task<IActionResult> CreateAsync()
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // переменная для хранения выбранного номера по списку по умолчанию
            short selectedIndex = 1;

            // создание выпадающего списка Форм обучения, в качестве аргументов:
            // элементы списка, номер элемента списка, его название и номер выбранного элемента
            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", selectedIndex);

            // передаем настроенный список с помощью ViewBag
            ViewBag.FormsOfStudy = formsOfStudy;

            // создание выпадающего списка Специальностей, который зависим от списка с Формами обучения
            // в качестве аргументов:
            // элементы списка (для текущей формы обучения), номер элемента списка, его название
            SelectList specialties = new(await _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == selectedIndex)
                .OrderBy(o => o.Code).ToListAsync(),
                "Id", "Code");

            // передаем настроенный список с помощью ViewBag
            ViewBag.Specialties = specialties;
            return View();
        }

        public async Task<IActionResult> GetItemsAsync(short id)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // с помощью частичного представления снова возвращаем список с элементами
            // (специальности для выбранного пользователем элемента списка формы обчения)
            return PartialView(
                _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == id)
                .OrderBy(o => o.Code).ToList());
        }

        // POST: Groups/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGroupViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.Groups
                .Where(f => f.Specialty.FormOfStudy.IdUser == user.Id &&
                    f.Name == model.Name &&
                    f.ClassTeacher == model.ClassTeacher &&
                    f.YearOfAdmission == model.YearOfAdmission &&
                    f.YearOfIssue == model.YearOfIssue &&
                    f.IdSpecialty == model.IdSpecialty).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеная группа уже существует");
            }

            if (model.YearOfIssue <= model.YearOfAdmission)
            {
                ModelState.AddModelError("", "Год выпуска должен быть больше, чем год поступления");
            }

            if (ModelState.IsValid)
            {
                Group group = new()
                {
                    IdSpecialty = model.IdSpecialty,
                    Name = model.Name,
                    CountOfStudents = model.CountOfStudents,
                    YearOfAdmission = model.YearOfAdmission,
                    YearOfIssue = model.YearOfIssue,
                    ClassTeacher = model.ClassTeacher,
                    ContactsTeacher = model.ContactsTeacher
                };

                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            short selectedIndex = 1;

            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", selectedIndex);

            ViewBag.FormsOfStudy = formsOfStudy;

            SelectList specialties = new(await _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == selectedIndex)
                .OrderBy(o => o.Code).ToListAsync(),
                "Id", "Code");

            ViewBag.Specialties = specialties;

            return View(model);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups.FindAsync(id);
            if (group == null)
            {
                return NotFound();
            }

            short idFormOfStudy = await _context.Specialties
                .Where(w => w.Id == group.IdSpecialty)
                .Select(s => s.IdFormOfStudy)
                .FirstOrDefaultAsync();

            EditGroupViewModel model = new()
            {
                Id = group.Id,
                IdFormOfStudy = idFormOfStudy,
                IdSpecialty = group.IdSpecialty,
                Name = group.Name,
                CountOfStudents = group.CountOfStudents,
                YearOfAdmission = group.YearOfAdmission,
                YearOfIssue = group.YearOfIssue,
                ClassTeacher = group.ClassTeacher,
                ContactsTeacher = group.ContactsTeacher
            };

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", idFormOfStudy);

            ViewBag.FormsOfStudy = formsOfStudy;

            SelectList specialties = new(await _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == idFormOfStudy)
                .OrderBy(o => o.Code).ToListAsync(),
                "Id", "Code");

            ViewBag.Specialties = specialties;

            return View(model);
        }

        // POST: Groups/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditGroupViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            Group group = await _context.Groups.FindAsync(id);

            if (id != group.Id)
            {
                return NotFound();
            }

            if (_context.Groups
                .Where(f => f.Specialty.FormOfStudy.IdUser == user.Id &&
                    f.Name == model.Name &&
                    f.ClassTeacher == model.ClassTeacher &&
                    f.YearOfAdmission == model.YearOfAdmission &&
                    f.YearOfIssue == model.YearOfIssue &&
                    f.IdSpecialty == model.IdSpecialty).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеная группа уже существует");
            }

            if (model.YearOfIssue < model.YearOfAdmission)
            {
                ModelState.AddModelError("", "Год выпуска должен быть больше, чем год поступления");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    group.IdSpecialty = model.IdSpecialty;
                    group.Name = model.Name;
                    group.CountOfStudents = model.CountOfStudents;
                    group.YearOfAdmission = model.YearOfAdmission;
                    group.YearOfIssue = model.YearOfIssue;
                    group.ClassTeacher = model.ClassTeacher;
                    group.ContactsTeacher = model.ContactsTeacher;
                    _context.Update(group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", model.IdFormOfStudy);

            ViewBag.FormsOfStudy = formsOfStudy;

            SelectList specialties = new(await _context.Specialties

EducateAppChu/Views/Groups/Create.cshtml
@model EducateAppChu.ViewModels.Groups.CreateGroupViewModel

@{
    ViewData["Title"] = "Создание - Группы";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Groups" asp-action="Index">Группы</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление группы
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*создание выпадающего списка, элемента select при помощи Html-хелпера*@
            <div class="form-group">
                <label asp-for="IdFormOfStudy" class="control-label"></label>
                @Html.DropDownListFor(m => m.IdFormOfStudy,@* для какого свойства модели*@
                    ViewBag.FormsOfStudy as SelectList,          /* получаем переданные данные через ViewBag*/
                    new { id = "formOfStudy", @class = "form-control" })     @* указываем дополнительные атрибуты для элемента*@
            </div>
            <div class="form-group">
                <label asp-for="IdSpecialty" class="control-label"></label>
                @Html.DropDownListFor(m => m.IdSpecialty,
                   ViewBag.Specialties as SelectList,
                   new { id = "specialty", @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountOfStudents" class="control-label"></label>
                <input asp-for="CountOfStudents" class="form-control" />
                <span asp-validation-for="CountOfStudents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfAdmission" class="control-label"></label>
                <input asp-for="YearOfAdmission" class="form-control" />
                <span asp-validation-for="YearOfAdmission" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfIssue" class="control-label"></label>
                <input asp-for="YearOfIssue" class="form-control" />
                <span asp-validation-for="YearOfIssue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassTeacher" class="control-label"></label>
                <input asp-for="ClassTeacher" class="form-control" />
                <span asp-validation-for="ClassTeacher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactsTeacher" class="control-label"></label>
                <input asp-for="ContactsTeacher" class="form-control" />
                <span asp-validation-for="ContactsTeacher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            // когда вызывается событие change для элемента управления
            // т.е. выбирается новый элемент списка
            $('#formOfStudy').change(function()
            {
                // получаем выбранный id
                var id = $(this).val();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetItems")/' + id,
                    success: function (data) {
                        // заменяем содержимое присланным частичным представлением
                        $('#specialty').replaceWith(data);
                    }
                });
            });
        })
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateAppChu/Views/Groups/Delete.cshtml
@model EducateAppChu.Models.Data.Group
@{
    ViewData["Title"] = "Удаление - Группы";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Groups" asp-action="Index">Группы</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление группы
</h3>

<div>
    <h4>
        Вы уверены, что желаете удалить запись?<br />
        Все связанные данные будут удалены!
    </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.CountOfStudents)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.CountOfStudents)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.YearOfAdmission)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.YearOfAdmission)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.YearOfIssue)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.YearOfIssue)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.ClassTeacher)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ClassTeacher)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.ContactsTeacher)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ContactsTeacher)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Specialty)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Specialty.Code)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Specialty.FormOfStudy)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Specialty.FormOfStudy.FormOfEdu)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </form>
</div>

EducateAppChu/Views/Groups/Details.cshtml
@model EducateAppChu.Models.Data.Group

<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Просмотр группы</h4>
        <button type="button" class="close" data-dismiss="modal">
            <i class="fas fa-times"></i>
        </button>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CountOfStudents)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CountOfStudents)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.YearOfAdmission)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.YearOfAdmission)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.YearOfIssue)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.YearOfIssue)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ClassTeacher)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ClassTeacher)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ContactsTeacher)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ContactsTeacher)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Specialty)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Specialty.Code)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Specialty.FormOfStudy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Specialty.FormOfStudy.FormOfEdu)
            </dd>
        </dl>
    </div>
</div>

EducateAppChu/Views/Groups/Edit.cshtml
@model EducateAppChu.ViewModels.Groups.EditGroupViewModel
@{
    ViewData["Title"] = "Изменение - Группы";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Groups" asp-action="Index">Группы</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение группы
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*создание выпадающего списка, элемента select при помощи Html-хелпера*@
            <div class="form-group">
                <label asp-for="IdFormOfStudy" class="control-label"></label>
                @Html.DropDownListFor(m => m.IdFormOfStudy,@* для какого свойства модели*@
                    ViewBag.FormsOfStudy as SelectList,          /* получаем переданные данные через ViewBag*/
                    new { id = "formOfStudy", @class = "form-control" })     @* указываем дополнительные атрибуты для элемента*@
            </div>
            <div class="form-group">
                <label asp-for="IdSpecialty" class="control-label"></label>
                @Html.DropDownListFor(m => m.IdSpecialty,
                   ViewBag.Specialties as SelectList,
                   new { id = "specialty", @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountOfStudents" class="control-label"></label>
                <input asp-for="CountOfStudents" class="form-control" />
                <span asp-validation-for="CountOfStudents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfAdmission" class="control-label"></label>
                <input asp-for="YearOfAdmission" class="form-control" />
                <span asp-validation-for="YearOfAdmission" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfIssue" class="control-label"></label>
                <input asp-for="YearOfIssue" class="form-control" />
                <span asp-validation-for="YearOfIssue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassTeacher" class="control-label"></label>
                <input asp-for="ClassTeacher" class="form-control" />
                <span asp-validation-for="ClassTeacher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactsTeacher" class="control-label"></label>
                <input asp-for="ContactsTeacher" class="form-control" />
                <span asp-validation-for="ContactsTeacher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            // когда вызывается событие change для элемента управления
            // т.е. выбирается новый элемент списка
            $('#formOfStudy').change(function()
            {
                // получаем выбранный id
                var id = $(this).val();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetItems")/' + id,
                    success: function (data) {
                        // заменяем содержимое присланным частичным представлением
                        $('#specialty').replaceWith(data);
                    }
                });
            });
        })
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateAppChu/Views/Groups/GetItems.cshtml
@model IEnumerable<EducateAppChu.Models.Data.Specialty>
<select id="specialty" name="IdSpecialty" class="form-control">
    @foreach (var item in Model)
    {
        <option value="@item.Id">@item.Code</option>
    }
</select> 